### ISSUE TITLE
maxChars set to 10

### ISSUE THREAD

**Issue by mikemerin** [learn-co-curriculum/react-forms-lab#8]
Unless we look closely at the test, we wouldn't know the maxChars is 10 vs. the normal 140 Twitter uses. This should be stated in the directions.

**Comment by Lukeghenco** [comment]
Hi @mikemerin, thank you for raising the issue. The idea with this test is to assume you could add any amount of characters in the form, but it can't exceed it. Since it is sent down as a prop it could be 1000, as this is just a dynamic value. That is why we didn't add a specific requirement in the lesson that it had to have a required PropType with a specific length.
